### ISSUE TITLE
Is the README accurate about owner/maintainer being JFrog?

### ISSUE THREAD

**Issue by oskapt** [jainishshah17/tugger#39]
The README says that this is maintained by JFrog and links to the JFrog/Tugger repo. That repo hasn't been updated in 2 years and is archived. Perhaps the statement in that line is no longer accurate?

**Comment by jainishshah17** [comment]
You can use this repo. We are actively maintaining this. I will update README.

**Comment by jainishshah17** [comment]
https://github.com/jainishshah17/tugger/pull/40
