### ISSUE TITLE
tugger with several private docker registry`s

### ISSUE THREAD

**Issue by degilq** [jainishshah17/tugger#4]
hi Jainish, congratulations for this work, we have a issue, how tugger work with several private docker registry`s in same k8s cluster with several namespaces?

**Comment by jainishshah17** [comment]
As of now Tugger supports only one docker registry in multiple namespaces. I will start working on implementing this feature to support multiple docker registries.

**Comment by degilq** [comment]
thanks Jainish, excellent work

**Comment by jainishshah17** [comment]
@degilq Can you try https://github.com/jainishshah17/tugger/pull/6
