### ISSUE TITLE
Allow all namespaces (ie, bypass the whitelist check)

### ISSUE THREAD

**Issue by pbar1** [jainishshah17/tugger#64]
I'd like to utilize Tugger across all namespaces in my cluster. It's not immediately clear from the docs whether this is possible, though I took a brief look at the code - it seems like the namespace whitelisting check will always happen, and it doesn't do any regex pattern matching.

Is this possible today, and if not, is it on the roadmap?

**Comment by kd7lxl** [comment]
The namespace whitelist is the inverse logic of what you expect. It defines the namespaces that tugger will ignore, allowing any image to run without mutation. `kube-system` is a typical example. Tugger runs on all non-whitelisted namespaces.

**Comment by pbar1** [comment]
Ah yes, I actually just realized this after posting it. The terminology is a bit confusing here. I was expecting _whitelist_ to mean _opt-in to Tugger_, whereas it actually means _opt-out_. Thanks!
