### ISSUE TITLE
Info-leveled logging logs the entire AdmissionReview

### ISSUE THREAD

**Issue by pbar1** [jainishshah17/tugger#65]
This is surprising, as it makes for very long log messages if the Pod manifest is contained in the AdmissionReview. I'd expect only the image before/after would be logged, for example. Also, it would be possible to leak secrets if they're explicitly set via K8s environment variables. I know that this isn't a best practice, but it _could_ happen, so best to protect oneself with defense in depth.

**Comment by kd7lxl** [comment]
I think you're referring to here:
https://github.com/jainishshah17/tugger/blob/bf209b8912003eba0df60f7158a68c7d45afe708/cmd/tugger/main.go#L114

And I agree, it would be more appropriate for `Trace` level.

**Comment by jainishshah17** [comment]
Please check #66.
